const DEFAULT_ITEMS = [
    { id: 'item01', name: 'Box clam', icon: 'https://hellokittyislandadventure.wiki.gg/images/9/96/Box_Clam.png?3421bb', count: 7 },
    { id: 'item02', name: 'Calming Crystal', icon: 'https://hellokittyislandadventure.wiki.gg/images/0/00/Calming_Crystal.png', count: 7 },
    { id: 'item03', name: 'Coconut', icon: 'https://hellokittyislandadventure.wiki.gg/images/2/2f/Coconut.png?adac49', count: 29 },
    { id: 'item04', name: 'Iron', icon: 'https://hellokittyislandadventure.wiki.gg/images/4/45/Iron.png?add0dd', count: 14 },
    { id: 'item05', name: 'Ribbon', icon: 'https://hellokittyislandadventure.wiki.gg/images/8/8c/Ribbon.png?8bf0e5&20240626203632', count: 2 },
    { id: 'item06', name: 'Rubber', icon: 'https://hellokittyislandadventure.wiki.gg/images/8/8e/Rubber.png', count: 7 },
    { id: 'item07', name: 'Starfish', icon: 'https://hellokittyislandadventure.wiki.gg/images/5/52/Starfish.png?e865ce', count: 17 },
    { id: 'item08', name: 'Apple', icon: 'https://hellokittyislandadventure.wiki.gg/images/7/7d/Apple.png?41a49c', count: 7 },
    { id: 'item09', name: 'Cinna Bloom', icon: 'https://hellokittyislandadventure.wiki.gg/images/e/e6/Cinna_Bloom.png?2435fd', count: 7 },
    { id: 'item10', name: 'Coral Milk', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/de/Coral_Milk.png?36b485', count: 15 },
    { id: 'item11', name: 'Magma Bloom', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/d5/Magma_Bloom.png?feb6f7', count: 7 },
    { id: 'item12', name: 'Moon Cheese', icon: 'https://hellokittyislandadventure.wiki.gg/images/a/a9/Moon_Cheese.png?1dd891', count: 11 },
    { id: 'item13', name: 'Pineapple', icon: 'https://hellokittyislandadventure.wiki.gg/images/f/fb/Pineapple.png?ad2764', count: 9 },
    { id: 'item14', name: 'Pumpkin', icon: 'https://hellokittyislandadventure.wiki.gg/images/6/64/Pumpkin.png?cc04d3', count: 7 },
    { id: 'item15', name: 'Snowcicle', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/da/Snowcicle.png?f66096', count: 7 },
    { id: 'item16', name: 'Spinip', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/d4/Spinip.png?a44263', count: 12 },
    { id: 'item17', name: 'Starfruit', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/db/Starfruit.png?db076a', count: 12 },
    { id: 'item18', name: 'Cactus Cream', icon: 'https://hellokittyislandadventure.wiki.gg/images/f/f0/Cactus_Cream.png?dd8f56', count: 12 },
    { id: 'item19', name: 'Fizzy Ore', icon: 'https://hellokittyislandadventure.wiki.gg/images/3/3b/Fizzy_Ore.png?404c3e', count: 60 },
    { id: 'item20', name: 'Lotus Blossom', icon: 'https://hellokittyislandadventure.wiki.gg/images/b/bc/Lotus_Blossom.png', count: 14 },
    { id: 'item21', name: 'Seed', icon: 'https://hellokittyislandadventure.wiki.gg/images/2/2b/Seed_Icon.png?4cbb1f', count: 24 },
    { id: 'item22', name: 'Stick', icon: 'https://hellokittyislandadventure.wiki.gg/images/a/aa/Stick.png?e68e82', count: 37 },
    { id: 'item23', name: 'Worm Tail', icon: 'https://hellokittyislandadventure.wiki.gg/images/0/06/Worm_Tail.png', count: 14 },
    { id: 'item24', name: 'Chocolate Coin', icon: 'https://hellokittyislandadventure.wiki.gg/images/b/b8/Chocolate_Coin.png?738212', count: 15 },
    { id: 'item25', name: 'Sakura', icon: 'https://hellokittyislandadventure.wiki.gg/images/f/f4/Sakura.png?1c413f', count: 22 },
    { id: 'item26', name: 'Swampmallow', icon: 'https://hellokittyislandadventure.wiki.gg/images/b/b6/Swampmallow.png?dce919', count: 15 },
    { id: 'item27', name: 'Toasted Almond', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/d3/Toasted_Almond.png?52ae9a', count: 15 },
    { id: 'item28', name: 'Glow Berry', icon: 'https://hellokittyislandadventure.wiki.gg/images/d/dc/Glow_Berry.png', count: 7 },
    { id: 'item29', name: 'Mushroom', icon: 'https://hellokittyislandadventure.wiki.gg/images/8/8c/Mushroom.png?e54ee7', count: 50 },
    { id: 'item30', name: 'Obsidian Shard', icon: 'https://hellokittyislandadventure.wiki.gg/images/f/f1/Obsidian_Shard.png?17c1a2', count: 50 },
    { id: 'item31', name: 'Pollen Puff', icon: 'https://hellokittyislandadventure.wiki.gg/images/3/3c/Pollen_Puff.png?10cc6d', count: 50 },
    { id: 'item32', name: 'Sand Dollar', icon: 'https://hellokittyislandadventure.wiki.gg/images/5/53/Sand_Dollar.png?bc3439', count: 50 },
    { id: 'item33', name: 'Seashell', icon: 'https://hellokittyislandadventure.wiki.gg/images/e/eb/Seashell.png?772184', count: 50 },
    { id: 'item34', name: 'Shiny', icon: 'https://hellokittyislandadventure.wiki.gg/images/1/10/Shiny.png?cde1d5', count: 50 },
];

export default DEFAULT_ITEMS;
